name: diabetrek_mealplanner_frontend

description: This is mealplanner fornt end project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  camera: ^0.10.0+3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  image_picker: ^0.8.4+11
  carousel_slider: ^4.1.1
  gap: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
